package storage

import "github.com/elei-io/pithosys/packages/search"

func PlatformUpstreamCaptureFields() []UpstreamCaptureFieldSeed {
	return []UpstreamCaptureFieldSeed{
		{ID: "upstream.head.etag", AttributePath: "upstream.etag", Enabled: true, Category: CaptureFieldCategoryRequired, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ETag", ValueType: search.TypeString},
		{ID: "upstream.head.size", AttributePath: "upstream.size", Enabled: true, Category: CaptureFieldCategoryRequired, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ContentLength", ValueType: search.TypeInteger},
		{ID: "upstream.head.last_modified", AttributePath: "upstream.last_modified", Enabled: true, Category: CaptureFieldCategoryRequired, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "LastModified", ValueType: search.TypeTimestamp},

		{ID: "upstream.head.header.accept_ranges", AttributePath: "upstream.header.accept_ranges", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "AcceptRanges", ValueType: search.TypeString},
		{ID: "upstream.head.header.cache_control", AttributePath: "upstream.header.cache_control", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "CacheControl", ValueType: search.TypeString},
		{ID: "upstream.head.header.content_type", AttributePath: "upstream.header.content_type", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ContentType", ValueType: search.TypeString},
		{ID: "upstream.head.header.content_disposition", AttributePath: "upstream.header.content_disposition", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ContentDisposition", ValueType: search.TypeString},
		{ID: "upstream.head.header.content_encoding", AttributePath: "upstream.header.content_encoding", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ContentEncoding", ValueType: search.TypeString},
		{ID: "upstream.head.header.content_language", AttributePath: "upstream.header.content_language", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ContentLanguage", ValueType: search.TypeString},

		{ID: "upstream.head.metadata_all", AttributePath: "upstream.metadata", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorMetadataAll, ExtractorRef: "*", ValueType: search.TypeString},

		{ID: "upstream.s3.storage_class", AttributePath: "upstream.s3.storage_class", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "StorageClass", ValueType: search.TypeString},
		{ID: "upstream.s3.version_id", AttributePath: "upstream.s3.version_id", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "VersionId", ValueType: search.TypeString},
		{ID: "upstream.s3.server_side_encryption", AttributePath: "upstream.s3.server_side_encryption", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ServerSideEncryption", ValueType: search.TypeString},
		{ID: "upstream.s3.sse_kms_key_id", AttributePath: "upstream.s3.sse_kms_key_id", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "SSEKMSKeyId", ValueType: search.TypeString},
		{ID: "upstream.s3.sse_customer_algorithm", AttributePath: "upstream.s3.sse_customer_algorithm", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "SSECustomerAlgorithm", ValueType: search.TypeString},
		{ID: "upstream.s3.sse_customer_key_md5", AttributePath: "upstream.s3.sse_customer_key_md5", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "SSECustomerKeyMD5", ValueType: search.TypeString},
		{ID: "upstream.s3.website_redirect_location", AttributePath: "upstream.s3.website_redirect_location", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "WebsiteRedirectLocation", ValueType: search.TypeString},
		{ID: "upstream.s3.expiration", AttributePath: "upstream.s3.expiration", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "Expiration", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_crc32", AttributePath: "upstream.s3.checksum_crc32", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumCRC32", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_crc32c", AttributePath: "upstream.s3.checksum_crc32c", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumCRC32C", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_crc64nvme", AttributePath: "upstream.s3.checksum_crc64nvme", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumCRC64NVME", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_sha1", AttributePath: "upstream.s3.checksum_sha1", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumSHA1", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_sha256", AttributePath: "upstream.s3.checksum_sha256", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumSHA256", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_sha512", AttributePath: "upstream.s3.checksum_sha512", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumSHA512", ValueType: search.TypeString},
		{ID: "upstream.s3.checksum_md5", AttributePath: "upstream.s3.checksum_md5", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ChecksumMD5", ValueType: search.TypeString},
		{ID: "upstream.s3.bucket_key_enabled", AttributePath: "upstream.s3.bucket_key_enabled", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "BucketKeyEnabled", ValueType: search.TypeBoolean},
		{ID: "upstream.s3.archive_status", AttributePath: "upstream.s3.archive_status", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ArchiveStatus", ValueType: search.TypeString},
		{ID: "upstream.s3.replication_status", AttributePath: "upstream.s3.replication_status", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ReplicationStatus", ValueType: search.TypeString},
		{ID: "upstream.s3.object_lock_mode", AttributePath: "upstream.s3.object_lock_mode", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ObjectLockMode", ValueType: search.TypeString},
		{ID: "upstream.s3.object_lock_legal_hold_status", AttributePath: "upstream.s3.object_lock_legal_hold_status", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ObjectLockLegalHoldStatus", ValueType: search.TypeString},
		{ID: "upstream.s3.object_lock_retain_until_date", AttributePath: "upstream.s3.object_lock_retain_until_date", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "ObjectLockRetainUntilDate", ValueType: search.TypeTimestamp},
		{ID: "upstream.s3.parts_count", AttributePath: "upstream.s3.parts_count", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "PartsCount", ValueType: search.TypeInteger},
		{ID: "upstream.s3.delete_marker", AttributePath: "upstream.s3.delete_marker", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceHead, ExtractorType: CaptureExtractorSDKField, ExtractorRef: "DeleteMarker", ValueType: search.TypeBoolean},

		{ID: "upstream.tagging_all", AttributePath: "upstream.tag", Enabled: true, Category: CaptureFieldCategoryOptional, CaptureSource: CaptureSourceTagging, ExtractorType: CaptureExtractorTaggingAll, ExtractorRef: "*", ValueType: search.TypeString},
	}
}
