// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  pithosysAttr = 7,
  pithosysRelation = 8,
  text = 9,
  Document = 1,
  PithosysAttr = 2,
  PithosysRelation = 3,
  Text = 4
