// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {pithosysOverlay} from "./pithosysql-tokens.ts"
import {pithosysqlHighlight} from "./pithosysql-highlight.ts"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QQQOPOOOOOP'#C^'#C^OOOP'#C_'#C_OOOP'#C`'#C`OOOP'#Cf'#CfOOOP'#Ca'#CaQQOPOOOOOP-E6_-E6_",
  stateData: "]~OVPOWQOXRO~O",
  goto: "jZPP[[[`PPPPfTSOUQUORVUTTOU",
  nodeNames: "⚠ Document PithosysAttr PithosysRelation Text",
  maxTerm: 10,
  propSources: [pithosysqlHighlight],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [pithosysOverlay],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
