// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  relicAttr = 7,
  relicRelation = 8,
  text = 9,
  Document = 1,
  RelicAttr = 2,
  RelicRelation = 3,
  Text = 4
