import datetime as dt
import uuid
from typing import Any, Protocol

from infra.db.models import StorageBackend, StorageBackendProbe


class StorageBackendStore(Protocol):
    def get(self, storage_backend_id: uuid.UUID) -> StorageBackend: ...

    def ensure_name_available(
        self, name: str, *, excluding_id: uuid.UUID | None = None
    ) -> None: ...

    def add(self, bucket: StorageBackend) -> None: ...

    def apply_updates(self, bucket: StorageBackend, values: dict[str, Any]) -> None: ...

    def delete(self, bucket: StorageBackend) -> None: ...

    def blob_count(self, storage_backend_id: uuid.UUID) -> int: ...

    def add_probe(self, probe: StorageBackendProbe) -> None: ...

    def delete_probes_older_than(self, cutoff: dt.datetime) -> int: ...

    def refresh(self, *entities: object) -> None: ...
