"""Filesystem subscription log event type constants."""

FILESYSTEM_EVENT_CREATED = "file.created"
FILESYSTEM_EVENT_CONTENT_UPDATED = "file.content_updated"
FILESYSTEM_EVENT_META_UPDATED = "file.meta_updated"
FILESYSTEM_EVENT_RENAMED = "file.renamed"
FILESYSTEM_EVENT_MOVED = "file.moved"
FILESYSTEM_EVENT_DELETED = "file.deleted"

FILESYSTEM_EVENT_FOLDER_CREATED = "folder.created"
FILESYSTEM_EVENT_FOLDER_RENAMED = "folder.renamed"
FILESYSTEM_EVENT_FOLDER_MOVED = "folder.moved"
FILESYSTEM_EVENT_FOLDER_DELETED = "folder.deleted"
FILESYSTEM_EVENT_FOLDER_DUPLICATED = "folder.duplicated"

FILESYSTEM_EVENT_TYPES = frozenset(
    {
        FILESYSTEM_EVENT_CREATED,
        FILESYSTEM_EVENT_CONTENT_UPDATED,
        FILESYSTEM_EVENT_META_UPDATED,
        FILESYSTEM_EVENT_RENAMED,
        FILESYSTEM_EVENT_MOVED,
        FILESYSTEM_EVENT_DELETED,
        FILESYSTEM_EVENT_FOLDER_CREATED,
        FILESYSTEM_EVENT_FOLDER_RENAMED,
        FILESYSTEM_EVENT_FOLDER_MOVED,
        FILESYSTEM_EVENT_FOLDER_DELETED,
        FILESYSTEM_EVENT_FOLDER_DUPLICATED,
    }
)

FILE_EVENT_ORIGINS = frozenset({"upload", "multipart", "copy", "duplicate"})
