"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-20 22:13:44.704223
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_file_meta_search_indexes() -> None:
    """GIN/expr indexes for JSONB meta search; autogenerate cannot emit these."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_files_meta_tags "
        "ON files USING GIN ((meta -> 'tags') jsonb_path_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_files_meta_keywords "
        "ON files USING GIN ((meta -> 'keywords') jsonb_path_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_files_meta_mimetype "
        "ON files ((meta ->> 'mimetype'))"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_files_meta_extension "
        "ON files ((meta ->> 'extension'))"
    )


def _drop_file_meta_search_indexes() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute("DROP INDEX IF EXISTS ix_files_meta_extension")
    op.execute("DROP INDEX IF EXISTS ix_files_meta_mimetype")
    op.execute("DROP INDEX IF EXISTS ix_files_meta_keywords")
    op.execute("DROP INDEX IF EXISTS ix_files_meta_tags")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_backends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=False),
    sa.Column('secret_access_key', sa.Text(), nullable=False),
    sa.Column('max_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), server_default='s3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('role IN (1,2)', name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.String(length=128), nullable=False),
    sa.Column('secret_access_key', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('job', sa.String(length=128), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('storage_backend_id', sa.Uuid(), nullable=True),
    sa.Column('blob_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('succeeded','failed','skipped')", name='ck_audit_events_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_backend_id'], ['storage_backends.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_actor_id_created_at', 'audit_events', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_batch_id_created_at', 'audit_events', ['batch_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_blob_id_created_at', 'audit_events', ['blob_id', 'created_at'], unique=False)
    op.create_index('ix_audit_events_created_at_id', 'audit_events', ['created_at', 'id'], unique=False)
    op.create_index('ix_audit_events_job_created_at', 'audit_events', ['job', 'created_at'], unique=False)
    op.create_index('ix_audit_events_operation_created_at', 'audit_events', ['operation', 'created_at'], unique=False)
    op.create_index('ix_audit_events_request_id', 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_events_status_created_at', 'audit_events', ['status', 'created_at'], unique=False)
    op.create_index('ix_audit_events_storage_backend_id_created_at', 'audit_events', ['storage_backend_id', 'created_at'], unique=False)
    op.create_table('blobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_backend_id', sa.Uuid(), nullable=False),
    sa.Column('bucket_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=64), nullable=False),
    sa.Column('refcount', sa.Integer(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_backend_id'], ['storage_backends.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blobs_accessed_at'), 'blobs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_blobs_storage_backend_id'), 'blobs', ['storage_backend_id'], unique=False)
    op.create_index('uq_blobs_content_hash_live', 'blobs', ['content_hash'], unique=True, postgresql_where=sa.text('refcount > 0'), sqlite_where=sa.text('refcount > 0'))
    op.create_table('filesystem_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filesystem_events_event_type_created_at', 'filesystem_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_filesystem_events_file_id_seq', 'filesystem_events', ['file_id', 'seq'], unique=False)
    op.create_index(op.f('ix_filesystem_events_folder_id'), 'filesystem_events', ['folder_id'], unique=False)
    op.create_index('ix_filesystem_events_folder_id_seq', 'filesystem_events', ['folder_id', 'seq'], unique=False)
    op.create_index('ix_filesystem_events_seq', 'filesystem_events', ['seq'], unique=True)
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('preferred_storage_backend_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_storage_backend_id'], ['storage_backends.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folders_parent_name')
    )
    op.create_index('uq_folders_single_root', 'folders', [sa.literal_column('(parent_id IS NULL)')], unique=True, postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.create_table('storage_backend_probes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_backend_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('put_ms', sa.Integer(), nullable=True),
    sa.Column('head_ms', sa.Integer(), nullable=True),
    sa.Column('get_ms', sa.Integer(), nullable=True),
    sa.Column('delete_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storage_backend_id'], ['storage_backends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storage_backend_probes_observed_at', 'storage_backend_probes', ['observed_at'], unique=False)
    op.create_index('ix_storage_backend_probes_storage_backend_id_observed_at', 'storage_backend_probes', ['storage_backend_id', 'observed_at'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('blob_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['blob_id'], ['blobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'name', name='uq_files_folder_name')
    )
    op.create_index(op.f('ix_files_actor_id'), 'files', ['actor_id'], unique=False)
    op.create_index(op.f('ix_files_blob_id'), 'files', ['blob_id'], unique=False)
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    _create_file_meta_search_indexes()
    op.create_table('folder_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(permissions & 1) != 0 OR permissions = 0', name='ck_folder_access_permissions_read_required'),
    sa.CheckConstraint('(permissions & ~15) = 0', name='ck_folder_access_permissions_known_bits'),
    sa.CheckConstraint('permissions > 0', name='ck_folder_access_permissions_positive'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'folder_id', name='uq_folder_access_actor_folder')
    )
    op.create_table('multipart_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('storage_backend_id', sa.Uuid(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_backend_id'], ['storage_backends.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multipart_uploads_actor_id'), 'multipart_uploads', ['actor_id'], unique=False)
    op.create_index('ix_multipart_uploads_actor_id_created_at', 'multipart_uploads', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_multipart_uploads_bucket_key', 'multipart_uploads', ['bucket_name', 'object_key'], unique=False)
    op.create_index(op.f('ix_multipart_uploads_folder_id'), 'multipart_uploads', ['folder_id'], unique=False)
    op.create_table('multipart_upload_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('bucket_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['multipart_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'part_number', name='uq_multipart_upload_parts_upload_part_number')
    )
    op.create_index(op.f('ix_multipart_upload_parts_upload_id'), 'multipart_upload_parts', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_multipart_upload_parts_upload_id'), table_name='multipart_upload_parts')
    op.drop_table('multipart_upload_parts')
    op.drop_index(op.f('ix_multipart_uploads_folder_id'), table_name='multipart_uploads')
    op.drop_index('ix_multipart_uploads_bucket_key', table_name='multipart_uploads')
    op.drop_index('ix_multipart_uploads_actor_id_created_at', table_name='multipart_uploads')
    op.drop_index(op.f('ix_multipart_uploads_actor_id'), table_name='multipart_uploads')
    op.drop_table('multipart_uploads')
    op.drop_table('folder_access')
    _drop_file_meta_search_indexes()
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_blob_id'), table_name='files')
    op.drop_index(op.f('ix_files_actor_id'), table_name='files')
    op.drop_table('files')
    op.drop_index('ix_storage_backend_probes_storage_backend_id_observed_at', table_name='storage_backend_probes')
    op.drop_index('ix_storage_backend_probes_observed_at', table_name='storage_backend_probes')
    op.drop_table('storage_backend_probes')
    op.drop_index('uq_folders_single_root', table_name='folders', postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.drop_table('folders')
    op.drop_index('ix_filesystem_events_seq', table_name='filesystem_events')
    op.drop_index('ix_filesystem_events_folder_id_seq', table_name='filesystem_events')
    op.drop_index(op.f('ix_filesystem_events_folder_id'), table_name='filesystem_events')
    op.drop_index('ix_filesystem_events_file_id_seq', table_name='filesystem_events')
    op.drop_index('ix_filesystem_events_event_type_created_at', table_name='filesystem_events')
    op.drop_table('filesystem_events')
    op.drop_index('uq_blobs_content_hash_live', table_name='blobs', postgresql_where=sa.text('refcount > 0'), sqlite_where=sa.text('refcount > 0'))
    op.drop_index(op.f('ix_blobs_storage_backend_id'), table_name='blobs')
    op.drop_index(op.f('ix_blobs_accessed_at'), table_name='blobs')
    op.drop_table('blobs')
    op.drop_index('ix_audit_events_storage_backend_id_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_status_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_request_id', table_name='audit_events')
    op.drop_index('ix_audit_events_operation_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_job_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at_id', table_name='audit_events')
    op.drop_index('ix_audit_events_blob_id_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_batch_id_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('access_keys')
    op.drop_table('users')
    op.drop_table('storage_backends')
    # ### end Alembic commands ###
