"""merge file metadata columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-10 02:21:01.839650
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.execute(
        """
        UPDATE files
        SET meta = jsonb_build_object(
            'schema_version', '1.0.0',
            'size', blobs.size_bytes,
            'extension',
                CASE
                    WHEN position('.' in reverse(files.name)) > 0
                    THEN lower(reverse(split_part(reverse(files.name), '.', 1)))
                    ELSE ''
                END,
            'mimetype',
                COALESCE(
                    files.parser_meta #>> '{file,mime_type}',
                    'application/octet-stream'
                ),
            'original_filename',
                COALESCE(files.ingest_meta ->> 'original_filename', files.name),
            'tags', '[]'::jsonb,
            'keywords', '[]'::jsonb,
            'summary', files.ingest_meta ->> 'summary',
            'kvs', files.ingest_meta - 'original_filename'
        )
        FROM blobs
        WHERE files.blob_id = blobs.id
        """
    )
    op.alter_column('files', 'meta', nullable=False)
    op.drop_column('files', 'ingest_meta')
    op.drop_column('files', 'parser_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('parser_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('ingest_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE files
        SET
            ingest_meta = jsonb_build_object(
                'original_filename',
                COALESCE(meta ->> 'original_filename', files.name)
            ) || COALESCE(meta -> 'kvs', '{}'::jsonb)
              || CASE
                    WHEN meta ->> 'summary' IS NULL THEN '{}'::jsonb
                    ELSE jsonb_build_object('summary', meta ->> 'summary')
                 END,
            parser_meta = jsonb_build_object(
                'file',
                jsonb_build_object(
                    'original_filename', COALESCE(meta ->> 'original_filename', files.name),
                    'size', COALESCE((meta ->> 'size')::bigint, blobs.size_bytes),
                    'mime_type', COALESCE(meta ->> 'mimetype', 'application/octet-stream'),
                    'extension', COALESCE(meta ->> 'extension', '')
                )
            )
        FROM blobs
        WHERE files.blob_id = blobs.id
        """
    )
    op.alter_column('files', 'ingest_meta', nullable=False)
    op.alter_column('files', 'parser_meta', nullable=False)
    op.drop_column('files', 'meta')
    # ### end Alembic commands ###
