"""drop bucket usage counters

Revision ID: 0007
Revises: 0006
Create Date: 2026-05-12 12:12:15.486708
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: str | Sequence[str] | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'current_size_bytes')
    op.drop_column('buckets', 'object_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('object_count', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('current_size_bytes', sa.BIGINT(), server_default='0', nullable=False))
    # ### end Alembic commands ###
