"""create events table

Revision ID: 0008
Revises: 0007
Create Date: 2026-05-12 13:53:40.498211
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0008'
down_revision: str | Sequence[str] | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('file_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('folder_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('blob_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_user_id'), 'events', ['actor_user_id'], unique=False)
    op.create_index('ix_events_created_at_id', 'events', ['created_at', 'id'], unique=False)
    op.create_index(op.f('ix_events_request_id'), 'events', ['request_id'], unique=False)
    op.create_index('ix_events_source_operation_created_at', 'events', ['source', 'operation', 'created_at'], unique=False)
    op.create_index('ix_events_status_created_at', 'events', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_status_created_at', table_name='events')
    op.drop_index('ix_events_source_operation_created_at', table_name='events')
    op.drop_index(op.f('ix_events_request_id'), table_name='events')
    op.drop_index('ix_events_created_at_id', table_name='events')
    op.drop_index(op.f('ix_events_actor_user_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
