"""rename events to audit events

Revision ID: 0009
Revises: 0008
Create Date: 2026-05-13 10:08:44.541455
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '0009'
down_revision: str | Sequence[str] | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.rename_table('events', 'audit_events')
    if bind.dialect.name == "postgresql":
        op.execute('ALTER INDEX ix_events_actor_user_id RENAME TO ix_audit_events_actor_user_id')
        op.execute('ALTER INDEX ix_events_created_at_id RENAME TO ix_audit_events_created_at_id')
        op.execute('ALTER INDEX ix_events_request_id RENAME TO ix_audit_events_request_id')
        op.execute('ALTER INDEX ix_events_status_created_at RENAME TO ix_audit_events_status_created_at')
        op.execute('ALTER INDEX events_pkey RENAME TO audit_events_pkey')
        op.execute('ALTER TABLE audit_events RENAME CONSTRAINT events_actor_user_id_fkey TO audit_events_actor_user_id_fkey')
    elif bind.dialect.name == "sqlite":
        # Index names are not renamed on SQLite; later migrations drop/create as needed.
        pass
    op.drop_index('ix_events_source_operation_created_at', table_name='audit_events')
    op.drop_column('audit_events', 'source')
    op.create_index('ix_audit_events_operation_created_at', 'audit_events', ['operation', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.add_column('audit_events', sa.Column('source', sa.String(length=128), nullable=False, server_default='relic_api'))
    op.drop_index('ix_audit_events_operation_created_at', table_name='audit_events')
    op.create_index('ix_events_source_operation_created_at', 'audit_events', ['source', 'operation', 'created_at'], unique=False)
    if bind.dialect.name == "postgresql":
        op.execute('ALTER TABLE audit_events RENAME CONSTRAINT audit_events_actor_user_id_fkey TO events_actor_user_id_fkey')
        op.execute('ALTER INDEX audit_events_pkey RENAME TO events_pkey')
        op.execute('ALTER INDEX ix_audit_events_status_created_at RENAME TO ix_events_status_created_at')
        op.execute('ALTER INDEX ix_audit_events_request_id RENAME TO ix_events_request_id')
        op.execute('ALTER INDEX ix_audit_events_created_at_id RENAME TO ix_events_created_at_id')
        op.execute('ALTER INDEX ix_audit_events_actor_user_id RENAME TO ix_events_actor_user_id')
    op.rename_table('audit_events', 'events')
    # ### end Alembic commands ###
