"""create file events

Revision ID: 0010
Revises: 0009
Create Date: 2026-05-13 11:51:17.556283
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: str | Sequence[str] | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offset', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), server_default='succeeded', nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_events_actor_user_id_created_at', 'file_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_file_events_event_type_created_at', 'file_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_file_events_file_id_created_at', 'file_events', ['file_id', 'created_at'], unique=False)
    op.create_index('ix_file_events_folder_id_created_at', 'file_events', ['folder_id', 'created_at'], unique=False)
    op.create_index('ix_file_events_offset', 'file_events', ['offset'], unique=True)
    op.create_index('ix_file_events_request_id', 'file_events', ['request_id'], unique=False)
    op.create_index('ix_file_events_status_created_at', 'file_events', ['status', 'created_at'], unique=False)
    op.create_index('uq_file_events_idempotency_key', 'file_events', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_file_events_idempotency_key', table_name='file_events', postgresql_where=sa.text('idempotency_key IS NOT NULL'), sqlite_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_file_events_status_created_at', table_name='file_events')
    op.drop_index('ix_file_events_request_id', table_name='file_events')
    op.drop_index('ix_file_events_offset', table_name='file_events')
    op.drop_index('ix_file_events_folder_id_created_at', table_name='file_events')
    op.drop_index('ix_file_events_file_id_created_at', table_name='file_events')
    op.drop_index('ix_file_events_event_type_created_at', table_name='file_events')
    op.drop_index('ix_file_events_actor_user_id_created_at', table_name='file_events')
    op.drop_table('file_events')
    # ### end Alembic commands ###
