"""add processor failure state

Revision ID: 0012
Revises: 0011
Create Date: 2026-05-13 13:02:52.470734
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0012'
down_revision: str | Sequence[str] | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processors', sa.Column('last_failed_event_id', sa.Uuid(), nullable=True))
    op.add_column('processors', sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processors', sa.Column('last_error_class', sa.String(length=255), nullable=True))
    op.add_column('processors', sa.Column('last_error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processors', 'last_error_message')
    op.drop_column('processors', 'last_error_class')
    op.drop_column('processors', 'last_failed_at')
    op.drop_column('processors', 'last_failed_event_id')
    # ### end Alembic commands ###
