"""create multipart uploads

Revision ID: 0017
Revises: 0016
Create Date: 2026-05-13 15:20:04.809274
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0017'
down_revision: str | Sequence[str] | None = '0016'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multipart_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_bucket_id', sa.Uuid(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_bucket_id'], ['buckets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_multipart_uploads_bucket_key', 'multipart_uploads', ['bucket_name', 'object_key'], unique=False)
    op.create_index(op.f('ix_multipart_uploads_folder_id'), 'multipart_uploads', ['folder_id'], unique=False)
    op.create_index(op.f('ix_multipart_uploads_uploaded_by'), 'multipart_uploads', ['uploaded_by'], unique=False)
    op.create_index('ix_multipart_uploads_uploaded_by_created_at', 'multipart_uploads', ['uploaded_by', 'created_at'], unique=False)
    op.create_table('multipart_upload_parts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('bucket_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('etag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['multipart_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'part_number', name='uq_multipart_upload_parts_upload_part_number')
    )
    op.create_index(op.f('ix_multipart_upload_parts_upload_id'), 'multipart_upload_parts', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_multipart_upload_parts_upload_id'), table_name='multipart_upload_parts')
    op.drop_table('multipart_upload_parts')
    op.drop_index('ix_multipart_uploads_uploaded_by_created_at', table_name='multipart_uploads')
    op.drop_index(op.f('ix_multipart_uploads_uploaded_by'), table_name='multipart_uploads')
    op.drop_index(op.f('ix_multipart_uploads_folder_id'), table_name='multipart_uploads')
    op.drop_index('ix_multipart_uploads_bucket_key', table_name='multipart_uploads')
    op.drop_table('multipart_uploads')
    # ### end Alembic commands ###
