"""replace access key secret hash

Revision ID: 0018
Revises: 0017
Create Date: 2026-05-13 21:52:44.385111
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '0018'
down_revision: str | Sequence[str] | None = '0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_keys', sa.Column('secret_access_key', sa.Text(), nullable=True))
    op.execute('DELETE FROM access_keys')
    with op.batch_alter_table('access_keys') as batch_op:
        batch_op.alter_column('secret_access_key', nullable=False)
        batch_op.drop_column('secret_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_keys', sa.Column('secret_hash', sa.LargeBinary(), nullable=True))
    op.execute('DELETE FROM access_keys')
    with op.batch_alter_table('access_keys') as batch_op:
        batch_op.alter_column('secret_hash', nullable=False)
        batch_op.drop_column('secret_access_key')
    # ### end Alembic commands ###
