"""greenfield actor enums multipart cleanup

Revision ID: 0019
Revises: 0018
Create Date: 2026-05-13 22:32:17.532784
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0019'
down_revision: str | Sequence[str] | None = '0018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM multipart_upload_parts')
    op.execute('DELETE FROM multipart_uploads')
    op.execute('DELETE FROM file_events')
    op.execute('DELETE FROM audit_events')
    op.execute('DELETE FROM files')
    op.execute('DELETE FROM folder_access')
    op.execute('DELETE FROM access_keys')
    op.create_check_constraint('ck_users_role', 'users', 'role IN (1,2)')
    op.create_check_constraint('ck_buckets_tier', 'buckets', 'tier IN (1,2,3,4)')
    op.create_check_constraint(
        'ck_folders_min_tier',
        'folders',
        'min_tier IS NULL OR min_tier IN (1,2,3,4)',
    )
    op.create_check_constraint(
        'ck_folder_access_permissions_positive',
        'folder_access',
        'permissions > 0',
    )
    op.create_check_constraint(
        'ck_folder_access_permissions_known_bits',
        'folder_access',
        '(permissions & ~15) = 0',
    )
    op.create_check_constraint(
        'ck_folder_access_permissions_read_required',
        'folder_access',
        '(permissions & 1) != 0 OR permissions = 0',
    )
    op.create_check_constraint(
        'ck_files_meta_extract_status',
        'files',
        'meta_extract_status IN (1,2,3,4)',
    )
    op.create_check_constraint(
        'ck_audit_events_status',
        'audit_events',
        "status IN ('succeeded','failed')",
    )
    op.create_check_constraint(
        'ck_file_events_status',
        'file_events',
        "status IN ('succeeded','failed')",
    )
    op.create_check_constraint(
        'ck_maintenance_events_status',
        'maintenance_events',
        "status IN ('succeeded','failed','skipped')",
    )
    op.create_check_constraint(
        'ck_processors_source',
        'processors',
        "source IN ('seed','admin')",
    )
    op.add_column('access_keys', sa.Column('actor_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('access_keys_user_id_fkey'), 'access_keys', type_='foreignkey')
    op.create_foreign_key('access_keys_actor_id_fkey', 'access_keys', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_keys', 'user_id')
    op.add_column('audit_events', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.drop_constraint(op.f('audit_events_actor_user_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key('audit_events_actor_id_fkey', 'audit_events', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_events', 'actor_user_id')
    op.add_column('file_events', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_file_events_actor_user_id_created_at'), table_name='file_events')
    op.create_index('ix_file_events_actor_id_created_at', 'file_events', ['actor_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('file_events_actor_user_id_fkey'), 'file_events', type_='foreignkey')
    op.create_foreign_key('file_events_actor_id_fkey', 'file_events', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('file_events', 'actor_user_id')
    op.add_column('files', sa.Column('actor_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.create_index(op.f('ix_files_actor_id'), 'files', ['actor_id'], unique=False)
    op.drop_constraint(op.f('files_uploaded_by_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key('files_actor_id_fkey', 'files', 'users', ['actor_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('files', 'uploaded_by')
    op.add_column('folder_access', sa.Column('actor_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('uq_folder_access_user_folder'), 'folder_access', type_='unique')
    op.create_unique_constraint('uq_folder_access_actor_folder', 'folder_access', ['actor_id', 'folder_id'])
    op.drop_constraint(op.f('folder_access_user_id_fkey'), 'folder_access', type_='foreignkey')
    op.create_foreign_key('folder_access_actor_id_fkey', 'folder_access', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('folder_access', 'user_id')
    op.add_column('multipart_uploads', sa.Column('actor_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_multipart_uploads_uploaded_by'), table_name='multipart_uploads')
    op.drop_index(op.f('ix_multipart_uploads_uploaded_by_created_at'), table_name='multipart_uploads')
    op.create_index(op.f('ix_multipart_uploads_actor_id'), 'multipart_uploads', ['actor_id'], unique=False)
    op.create_index('ix_multipart_uploads_actor_id_created_at', 'multipart_uploads', ['actor_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('multipart_uploads_uploaded_by_fkey'), 'multipart_uploads', type_='foreignkey')
    op.create_foreign_key('multipart_uploads_actor_id_fkey', 'multipart_uploads', 'users', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('multipart_uploads', 'file_name')
    op.drop_column('multipart_uploads', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM multipart_upload_parts')
    op.execute('DELETE FROM multipart_uploads')
    op.execute('DELETE FROM file_events')
    op.execute('DELETE FROM audit_events')
    op.execute('DELETE FROM files')
    op.execute('DELETE FROM folder_access')
    op.execute('DELETE FROM access_keys')
    op.execute('ALTER TABLE processors DROP CONSTRAINT IF EXISTS ck_processors_source')
    op.execute(
        'ALTER TABLE maintenance_events '
        'DROP CONSTRAINT IF EXISTS ck_maintenance_events_status'
    )
    op.execute('ALTER TABLE file_events DROP CONSTRAINT IF EXISTS ck_file_events_status')
    op.execute('ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS ck_audit_events_status')
    op.execute('ALTER TABLE files DROP CONSTRAINT IF EXISTS ck_files_meta_extract_status')
    op.execute(
        'ALTER TABLE folder_access '
        'DROP CONSTRAINT IF EXISTS ck_folder_access_permissions_read_required'
    )
    op.execute(
        'ALTER TABLE folder_access '
        'DROP CONSTRAINT IF EXISTS ck_folder_access_permissions_known_bits'
    )
    op.execute(
        'ALTER TABLE folder_access '
        'DROP CONSTRAINT IF EXISTS ck_folder_access_permissions_positive'
    )
    op.execute('ALTER TABLE folders DROP CONSTRAINT IF EXISTS ck_folders_min_tier')
    op.execute('ALTER TABLE buckets DROP CONSTRAINT IF EXISTS ck_buckets_tier')
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_role')
    op.add_column('multipart_uploads', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('multipart_uploads', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('multipart_uploads_actor_id_fkey', 'multipart_uploads', type_='foreignkey')
    op.create_foreign_key(op.f('multipart_uploads_uploaded_by_fkey'), 'multipart_uploads', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_multipart_uploads_actor_id_created_at', table_name='multipart_uploads')
    op.drop_index(op.f('ix_multipart_uploads_actor_id'), table_name='multipart_uploads')
    op.create_index(op.f('ix_multipart_uploads_uploaded_by_created_at'), 'multipart_uploads', ['uploaded_by', 'created_at'], unique=False)
    op.create_index(op.f('ix_multipart_uploads_uploaded_by'), 'multipart_uploads', ['uploaded_by'], unique=False)
    op.drop_column('multipart_uploads', 'actor_id')
    op.add_column('folder_access', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('folder_access_actor_id_fkey', 'folder_access', type_='foreignkey')
    op.create_foreign_key(op.f('folder_access_user_id_fkey'), 'folder_access', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_folder_access_actor_folder', 'folder_access', type_='unique')
    op.create_unique_constraint(op.f('uq_folder_access_user_folder'), 'folder_access', ['user_id', 'folder_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('folder_access', 'actor_id')
    op.add_column('files', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('files_actor_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_uploaded_by_fkey'), 'files', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_files_actor_id'), table_name='files')
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.drop_column('files', 'actor_id')
    op.add_column('file_events', sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('file_events_actor_id_fkey', 'file_events', type_='foreignkey')
    op.create_foreign_key(op.f('file_events_actor_user_id_fkey'), 'file_events', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_file_events_actor_id_created_at', table_name='file_events')
    op.create_index(op.f('ix_file_events_actor_user_id_created_at'), 'file_events', ['actor_user_id', 'created_at'], unique=False)
    op.drop_column('file_events', 'actor_id')
    op.add_column('audit_events', sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('audit_events_actor_id_fkey', 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_actor_user_id_fkey'), 'audit_events', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.drop_column('audit_events', 'actor_id')
    op.add_column('access_keys', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('access_keys_actor_id_fkey', 'access_keys', type_='foreignkey')
    op.create_foreign_key(op.f('access_keys_user_id_fkey'), 'access_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('access_keys', 'actor_id')
    # ### end Alembic commands ###
