"""drop bucket tier and folder min_tier; add bucket_probes, blob.migrated_at, folder.preferred_bucket_id

Revision ID: 0020
Revises: 0019
Create Date: 2026-05-13 23:13:22.082984
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0020'
down_revision: str | Sequence[str] | None = '0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket_probes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bucket_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('put_ms', sa.Integer(), nullable=True),
    sa.Column('head_ms', sa.Integer(), nullable=True),
    sa.Column('get_ms', sa.Integer(), nullable=True),
    sa.Column('delete_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['buckets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bucket_probes_bucket_id_observed_at', 'bucket_probes', ['bucket_id', 'observed_at'], unique=False)
    op.create_index('ix_bucket_probes_observed_at', 'bucket_probes', ['observed_at'], unique=False)
    op.add_column('blobs', sa.Column('migrated_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('buckets') as batch_op:
        batch_op.drop_column('probe_latency_head_ms')
        batch_op.drop_column('probe_latency_put_ms')
        batch_op.drop_column('probe_latency_delete_ms')
        batch_op.drop_column('tier')
        batch_op.drop_column('probe_latency_get_ms')
    with op.batch_alter_table('folders') as batch_op:
        batch_op.add_column(sa.Column('preferred_bucket_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'folders_preferred_bucket_id_fkey',
            'buckets',
            ['preferred_bucket_id'],
            ['id'],
            ondelete='SET NULL',
        )
        batch_op.drop_column('min_tier')
        batch_op.drop_column('cooldown_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('cooldown_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('folders', sa.Column('min_tier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'preferred_bucket_id')
    op.add_column('buckets', sa.Column('probe_latency_get_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buckets', sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buckets', sa.Column('probe_latency_delete_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buckets', sa.Column('probe_latency_put_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buckets', sa.Column('probe_latency_head_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blobs', 'migrated_at')
    op.drop_index('ix_bucket_probes_observed_at', table_name='bucket_probes')
    op.drop_index('ix_bucket_probes_bucket_id_observed_at', table_name='bucket_probes')
    op.drop_table('bucket_probes')
    # ### end Alembic commands ###
