"""add processor dispatch generation

Revision ID: 0021
Revises: 0020
Create Date: 2026-05-14 00:39:45.390220
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0021'
down_revision: str | Sequence[str] | None = '0020'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processors', sa.Column('dispatch_generation', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processors', 'dispatch_generation')
    # ### end Alembic commands ###
