"""drop meta_extract_status; add processor mimetype/extension filters

Revision ID: 0022
Revises: 0021
Create Date: 2026-05-14 10:59:16.166722
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0022'
down_revision: str | Sequence[str] | None = '0021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'meta_extract_status')
    op.add_column('processors', sa.Column('mimetype_prefixes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('processors', sa.Column('extensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processors', 'extensions')
    op.drop_column('processors', 'mimetype_prefixes')
    op.add_column('files', sa.Column('meta_extract_status', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
