"""create processor event runs

Revision ID: 0023
Revises: 0022
Create Date: 2026-05-14 11:41:27.451932
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0023'
down_revision: str | Sequence[str] | None = '0022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor_event_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('processor_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('dispatch_generation', sa.Integer(), nullable=False),
    sa.Column('event_offset', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('ordering_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','succeeded','failed')", name='ck_processor_event_runs_status'),
    sa.ForeignKeyConstraint(['event_id'], ['file_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processor_id'], ['processors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processor_id', 'dispatch_generation', 'event_id', name='uq_processor_event_runs_processor_generation_event')
    )
    op.create_index('ix_processor_event_runs_processor_generation_status', 'processor_event_runs', ['processor_id', 'dispatch_generation', 'status'], unique=False)
    op.create_index('ix_processor_event_runs_processor_generation_subject', 'processor_event_runs', ['processor_id', 'dispatch_generation', 'ordering_key'], unique=False)
    op.create_index('ix_processor_event_runs_processor_status', 'processor_event_runs', ['processor_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processor_event_runs_processor_status', table_name='processor_event_runs')
    op.drop_index('ix_processor_event_runs_processor_generation_subject', table_name='processor_event_runs')
    op.drop_index('ix_processor_event_runs_processor_generation_status', table_name='processor_event_runs')
    op.drop_table('processor_event_runs')
    # ### end Alembic commands ###
