"""drop_eventing_add_blob_sniff_fields

Revision ID: 0024
Revises: 0023
Create Date: 2026-05-20 10:16:50.299937
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0024'
down_revision: str | Sequence[str] | None = '0023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        op.drop_table('processor_event_runs')
        op.drop_table('processors')
        op.drop_table('audit_events')
        op.drop_table('file_events')
    else:
        op.drop_index(op.f('ix_processor_event_runs_processor_generation_status'), table_name='processor_event_runs')
        op.drop_index(op.f('ix_processor_event_runs_processor_generation_subject'), table_name='processor_event_runs')
        op.drop_index(op.f('ix_processor_event_runs_processor_status'), table_name='processor_event_runs')
        op.drop_table('processor_event_runs')
        op.drop_index(op.f('ix_processors_enabled'), table_name='processors')
        op.drop_index(op.f('ix_processors_kind'), table_name='processors')
        op.drop_table('processors')
        op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_created_at_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_operation_created_at'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
        op.drop_index(op.f('ix_audit_events_status_created_at'), table_name='audit_events')
        op.drop_table('audit_events')
        op.drop_index(op.f('ix_file_events_actor_id_created_at'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_event_type_created_at'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_file_id_created_at'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_folder_id_created_at'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_offset'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_request_id'), table_name='file_events')
        op.drop_index(op.f('ix_file_events_status_created_at'), table_name='file_events')
        op.drop_index(
            op.f('uq_file_events_idempotency_key'),
            table_name='file_events',
            postgresql_where='(idempotency_key IS NOT NULL)',
        )
        op.drop_table('file_events')
    op.add_column(
        'blobs',
        sa.Column(
            'mimetype',
            sa.String(length=255),
            nullable=False,
            server_default='application/octet-stream',
        ),
    )
    op.add_column(
        'blobs',
        sa.Column('extension', sa.String(length=64), nullable=False, server_default=''),
    )
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.alter_column('blobs', 'mimetype', server_default=None)
        op.alter_column('blobs', 'extension', server_default=None)
    else:
        with op.batch_alter_table('blobs') as batch_op:
            batch_op.alter_column('mimetype', server_default=None)
            batch_op.alter_column('extension', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blobs', 'extension')
    op.drop_column('blobs', 'mimetype')
    op.create_table('file_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('offset', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), server_default=sa.text("'succeeded'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['succeeded'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_file_events_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('file_events_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('file_events_pkey'))
    )
    op.create_index(op.f('uq_file_events_idempotency_key'), 'file_events', ['idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_index(op.f('ix_file_events_status_created_at'), 'file_events', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_events_request_id'), 'file_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_file_events_offset'), 'file_events', ['offset'], unique=True)
    op.create_index(op.f('ix_file_events_folder_id_created_at'), 'file_events', ['folder_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_events_file_id_created_at'), 'file_events', ['file_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_events_event_type_created_at'), 'file_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_file_events_actor_id_created_at'), 'file_events', ['actor_id', 'created_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['succeeded'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_audit_events_status')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_events_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('ix_audit_events_status_created_at'), 'audit_events', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_operation_created_at'), 'audit_events', ['operation', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at_id'), 'audit_events', ['created_at', 'id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_table('processor_event_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('processor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dispatch_generation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_offset', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ordering_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['queued'::character varying, 'succeeded'::character varying, 'failed'::character varying]::text[])", name=op.f('ck_processor_event_runs_status')),
    sa.ForeignKeyConstraint(['event_id'], ['file_events.id'], name=op.f('processor_event_runs_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processor_id'], ['processors.id'], name=op.f('processor_event_runs_processor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('processor_event_runs_pkey')),
    sa.UniqueConstraint('processor_id', 'dispatch_generation', 'event_id', name=op.f('uq_processor_event_runs_processor_generation_event'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_processor_event_runs_processor_status'), 'processor_event_runs', ['processor_id', 'status'], unique=False)
    op.create_index(op.f('ix_processor_event_runs_processor_generation_subject'), 'processor_event_runs', ['processor_id', 'dispatch_generation', 'ordering_key'], unique=False)
    op.create_index(op.f('ix_processor_event_runs_processor_generation_status'), 'processor_event_runs', ['processor_id', 'dispatch_generation', 'status'], unique=False)
    op.create_table('processors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('subscribed_event_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_committed_offset', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_committed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_failed_event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_error_class', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('folder_scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('dispatch_generation', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('mimetype_prefixes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('extensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.CheckConstraint("source::text = ANY (ARRAY['seed'::character varying, 'admin'::character varying]::text[])", name=op.f('ck_processors_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('processors_pkey')),
    sa.UniqueConstraint('name', name=op.f('processors_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_processors_kind'), 'processors', ['kind'], unique=False)
    op.create_index(op.f('ix_processors_enabled'), 'processors', ['enabled'], unique=False)
    # ### end Alembic commands ###
