"""add_bucket_storage_kind

Revision ID: 0026
Revises: 0025
Create Date: 2026-05-20 11:52:48.002706
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0026'
down_revision: str | Sequence[str] | None = '0025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('storage_kind', sa.String(length=32), server_default='s3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'storage_kind')
    # ### end Alembic commands ###
