"""create_file_events_subscription_log

Revision ID: 0028
Revises: 0027
Create Date: 2026-05-20 20:45:30.049983
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0028'
down_revision: str | Sequence[str] | None = '0027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_events', schema=None) as batch_op:
        batch_op.create_index('ix_file_events_event_type_created_at', ['event_type', 'created_at'], unique=False)
        batch_op.create_index('ix_file_events_file_id_seq', ['file_id', 'seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_events_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index('ix_file_events_folder_id_seq', ['folder_id', 'seq'], unique=False)
        batch_op.create_index('ix_file_events_seq', ['seq'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_events', schema=None) as batch_op:
        batch_op.drop_index('ix_file_events_seq')
        batch_op.drop_index('ix_file_events_folder_id_seq')
        batch_op.drop_index(batch_op.f('ix_file_events_folder_id'))
        batch_op.drop_index('ix_file_events_file_id_seq')
        batch_op.drop_index('ix_file_events_event_type_created_at')

    op.drop_table('file_events')
    # ### end Alembic commands ###
