import hashlib

from enums import Permission

API_PREFIX = "/api"

FILE_INFO_PREFIX_BYTES = 4096

S3_SIGNING_ALGORITHM = "AWS4-HMAC-SHA256"
S3_SIGNING_SERVICE = "s3"
S3_SIGNING_TERMINATOR = "aws4_request"
S3_UNSIGNED_PAYLOAD = "UNSIGNED-PAYLOAD"
S3_USER_BINDING_HEADER = "x-amz-meta-pithosys-user"
S3_PITHOSYS_FILE_ID_HEADER = "x-amz-meta-pithosys-file-id"
S3_PITHOSYS_BLOB_ID_HEADER = "x-amz-meta-pithosys-blob-id"
S3_PITHOSYS_FOLDER_ID_HEADER = "x-amz-meta-pithosys-folder-id"
S3_PITHOSYS_META_HEADER = "x-amz-meta-pithosys-meta"
S3_USER_METADATA_MAX_BYTES = 2048
S3_EMPTY_PAYLOAD_HASH = hashlib.sha256(b"").hexdigest()
S3_MAX_HEADER_SIGNATURE_AGE_SECONDS = 15 * 60

S3_METADATA_DIRECTIVE_COPY = "COPY"
S3_METADATA_DIRECTIVE_REPLACE = "REPLACE"
S3_MULTIPART_MIN_PART_NUMBER = 1
S3_MULTIPART_MAX_PART_NUMBER = 10_000
S3_LISTING_DEFAULT_MAX_KEYS = 1000
S3_LISTING_MAX_KEYS_LIMIT = 1000

SEARCH_SUPPORTED_META_OPS = frozenset({"eq", "neq", "gte", "lte", "gt", "lt"})
SEARCH_SUPPORTED_SORT_FIELDS = frozenset({"name", "size", "created_at", "updated_at"})
SEARCH_SUPPORTED_ORDERS = frozenset({"asc", "desc"})
SEARCH_DEFAULT_LIMIT = 50
SEARCH_MAX_LIMIT = 200
SEARCH_DEFAULT_FACET_TOP = 20
SEARCH_MAX_FACET_TOP = 100

AUDIT_EVENT_DEFAULT_LIMIT = 50
AUDIT_EVENT_MAX_LIMIT = 200

FILESYSTEM_EVENT_DEFAULT_LIMIT = 50
FILESYSTEM_EVENT_MAX_LIMIT = 200

FOLDER_ACCESS_PERMISSION_MASK = (
    Permission.READ | Permission.WRITE | Permission.DELETE | Permission.ENRICH
)
FOLDER_ACCESS_ALL_PERMISSIONS = int(FOLDER_ACCESS_PERMISSION_MASK)

FILESYSTEM_DEFAULT_LIST_LIMIT = 50
FILESYSTEM_MAX_LIST_LIMIT = 200
FILESYSTEM_LIST_SORT_FIELDS = frozenset({"name", "updated_at", "size", "mimetype"})
FILESYSTEM_LIST_SORT_ORDERS = frozenset({"asc", "desc"})

ENV_TRUTHY_VALUES = {"true", "1", "yes", "y", "on"}
ENV_FALSY_VALUES = {"false", "0", "no", "n", "off"}
