import datetime as dt
import uuid
from typing import Any, Protocol

from infra.db.models import Bucket, BucketProbe


class BucketStore(Protocol):
    def get(self, bucket_id: uuid.UUID) -> Bucket: ...

    def ensure_name_available(
        self, name: str, *, excluding_id: uuid.UUID | None = None
    ) -> None: ...

    def add(self, bucket: Bucket) -> None: ...

    def apply_updates(self, bucket: Bucket, values: dict[str, Any]) -> None: ...

    def delete(self, bucket: Bucket) -> None: ...

    def blob_count(self, bucket_id: uuid.UUID) -> int: ...

    def add_probe(self, probe: BucketProbe) -> None: ...

    def delete_probes_older_than(self, cutoff: dt.datetime) -> int: ...

    def refresh(self, *entities: object) -> None: ...
