import uuid
from typing import Protocol

from application.context import Actor
from infra.db.models import File, Folder


class FileStore(Protocol):
    def ensure_name_available(self, folder_id: uuid.UUID, name: str) -> None: ...

    def save(self, file: File) -> None: ...

    def ensure_blob_loaded(self, file: File) -> File: ...

    def list_in_folders(self, folder_ids: list[uuid.UUID]) -> list[File]: ...

    def delete_in_folders(self, folder_ids: list[uuid.UUID]) -> None: ...

    def add(self, file: File) -> None: ...

    def delete(self, file: File) -> None: ...

    def adjust_blob_refcounts(self, deltas: dict[uuid.UUID, int]) -> None: ...
