import uuid
from typing import Protocol

from infra.db.models import User


class UserStore(Protocol):
    def list_all(self) -> list[User]: ...

    def get(self, user_id: uuid.UUID) -> User: ...

    def ensure_email_available(
        self, email: str, *, excluding_user_id: uuid.UUID | None = None
    ) -> None: ...

    def add(self, user: User) -> None: ...

    def save(self, user: User) -> None: ...

    def delete(self, user: User) -> None: ...

    def has_uploaded_files(self, user_id: uuid.UUID) -> bool: ...
